### ISSUE TITLE
Missing required libraries ?

### ISSUE THREAD

**Issue by Mappy-team-LBS** [valhalla/mjolnir#190]
Hello,

In the documentation, there is : 

sudo apt-get install -y autoconf automake libtool make gcc-4.8 g++-4.8 libboost1.54-dev libboost-program-options1.54-dev libboost-filesystem1.54-dev libboost-system1.54-dev protobuf-compiler libprotobuf-dev lua5.2 liblua5.2-dev

But launching ./configure fails, because some required libraries are missing.

The first one is libsqlite3-dev. I installed it.

The second one seems to be libgeos : 
checking for geos-config... no
configure: error: geos-config does not exist or it is not an exectuable file

I installed libgeos-dev, but launching ./configure produces : 

checking for geos-config... /usr/bin/geos-config
checking for geos libraries... checking geos/version.h usability... no
checking geos/version.h presence... no
checking for geos/version.h... no
configure: error: development headers for geos not found

Midgard and Baldr are already installed. From what I understood, they are the only Valhalla libraries required for Mjolnir.

PS / take advantage of this issue to tell you that I make the all Valhalla compilations with Boost 1.55.0.

**Comment by Mappy-team-LBS** [comment]
OK, here are the needed libraries not given in the doc : 

libsqlite3-dev
libgeos++-dev
libspatialite-dev

**Comment by kevinkreiser** [comment]
Indeed, we have been falling behind on keeping the documentation up with the code. We had actually updated this doc: https://github.com/valhalla/chef-valhalla

Which covers how to install all of the software but forgot to update the specifc project. If ever you aren't sure what dependencies you need make sure to take a look at the specific project's circle.yml file.
