### ISSUE TITLE
test_ways.bin(mmap): Invalid argument

### ISSUE THREAD

**Issue by ptpt** [valhalla/mjolnir#253]
Hi,

This issue has been around for a while on my machine. The other Valhalla libraries were cloned and installed weeks ago. Today I tried to update everything with following comamnd:
```
# git pull all of them
for repo in midgard baldr sif mjolnir; do
     cd $repo
     ./autogen.sh
     ./configure CPPFLAGS=-DBOOST_SPIRIT_THREADSAFE
     make
     sudo make install
     cd ..
done
```

Here is the test report:
```
$ make test
$ cat ./test-suite.log 
=====================================
   mjolnir 0.0.1: ./test-suite.log
=====================================

# TOTAL: 11
# PASS:  10
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test/graphparser
======================

=== Testing parser ===
                        DoConfig  [PASS]
      TestBollardsGatesAndAccess2015/06/05 07:40:20.905730 [INFO] Parsing files: test/data/liechtenstein-latest.osm.pbf
2015/06/05 07:40:20.906850 [INFO] Parsing ways...
terminate called after throwing an instance of 'std::runtime_error'
  what():  test_ways.bin(mmap): Invalid argument
```

Command output:
```
$ pbfgraphbuilder -c conf/valhalla.json switzerland-latest.osm.pbf
2015/06/05 07:44:40.880805 [INFO] Parsing files: switzerland-latest.osm.pbf
2015/06/05 07:44:40.883256 [INFO] Parsing ways...
terminate called after throwing an instance of 'std::runtime_error'
  what():  way_nodes.bin(mmap): Invalid argument
Aborted (core dumped)
```

My machine information (VirtualBox):
```
$ uname -a
Linux vagrant-ubuntu-trusty-64 3.13.0-52-generic #86-Ubuntu SMP Mon May 4 04:32:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Any further information, let me know.

/Tao

**Comment by kevinkreiser** [comment]
can you link me to the image you are using for vagrant/virtual-box? ill try to reproduce it

**Comment by kevinkreiser** [comment]
acutally have you tried running it in a different directory? ie not in a dir that is on the host machine as well? this seemed relevant: http://stackoverflow.com/questions/18420473/invalid-argument-for-read-write-mmap

**Comment by ptpt** [comment]
@kevinkreiser I think the link is very relevant. I moved the mjolnir directory out of shared folder, the problem solved. It seems that you have to avoid writing `way_nodes.bin` to the shared folder.

If you still need to test it, use this vagrant box https://atlas.hashicorp.com/ubuntu/boxes/trusty64

Thanks.
