### ISSUE TITLE
Unintentional no-op? 

### ISSUE THREAD

**Issue by fsaric** [valhalla/mjolnir#269]
In osmway.cc line 323:
```
// Set no thru traffic flag.
void OSMWay::set_no_thru_traffic(const bool no_thru_traffic) {
  attributes_.fields.no_thru_traffic;
}
```

The flag is never set. I guess this is not intentional?

The same goes for node_expander.h, line 105 (but that one kind of seems intentional?).

**Comment by gknisely** [comment]
Thanks.  Fixed and creating a PR
