### ISSUE TITLE
Missing 'time' value for first 'maneuver'

### ISSUE THREAD

**Issue by costales** [valhalla/mjolnir#311]
Hi!

For this call:
https://valhalla.mapzen.com/route?json={"locations":[{"lat":43.47869000000001,"lon":-5.680983333333334},{"lat":43.5450394,"lon":-5.6626443}],"costing":"auto"}&api_key=valhalla-xxxxxx

it's returning this route:
http://paste.ubuntu.com/12904171/

For the first maneuver, the 'lenght' is correct, but the 'time' can't be 0 for 5,3km :)
           "maneuvers":[
               {
                  "begin_shape_index":0,
                  "length":5.347,
                  **"time":0**,
                  "type":1,
                  "end_shape_index":89,
                  "instruction":"Go north on AS-I.",
                  "verbal_pre_transition_instruction":"Go north on AS-I for 5.3 kilometers.",
                  "street_names":[
                     "AS-I"
                  ]
               }

Best regards and thanks in advance!

**Comment by dgearhart** [comment]
@dnesbitt61 - were you looking at similar bug?

**Comment by costales** [comment]
Thanks a lot :)
