### ISSUE TITLE
Bad indications in a few instructions

### ISSUE THREAD

**Issue by costales** [valhalla/mjolnir#313]
Hi!
I found a few weird indications with this route:
https://valhalla.mapzen.com/route?json={"locations":[{"lat":43.306357,"lon":-5.688225},{"lat":43.532201,"lon":-5.66112}],"costing":"auto"}&api_key=valhalla-xxxxx

In this roundabout, the exit should be 3th, not 1st:
![photo192226415749474600](https://cloud.githubusercontent.com/assets/5886786/10770080/b4e1346a-7ce9-11e5-8721-73c00d09c612.jpg)
OSM: http://www.openstreetmap.org/edit?editor=potlatch2#map=20/43.30364/-5.68962
               {
                  "roundabout_exit_count":1,
                  "begin_shape_index":21,
                  "street_names":[
                     "Glorieta de Langreo Centro",
                     "AS-246"
                  ],
                  "time":12,
                  "type":26,
                  "end_shape_index":30,
                  "instruction":"Enter the roundabout and take the 1st exit.",
                  "length":0.071,
                  "verbal_transition_alert_instruction":"Enter roundabout.",
                  "verbal_pre_transition_instruction":"Enter the roundabout and take the 1st exit."
               },

In this there shouldn't be an exit:
![photo192226415749474602](https://cloud.githubusercontent.com/assets/5886786/10770085/b8ac741a-7ce9-11e5-8935-473d9ff81c05.jpg)
OSM: http://www.openstreetmap.org/edit?editor=potlatch2#map=20/43.31673/-5.70715
            {
                  "begin_shape_index":135,
                  "street_names":[
                     "AS-117",
                     "Enlace de Barros"
                  ],
                  "time":4,
                  "type":20,
                  "end_shape_index":137,
                  "instruction":"Take the exit on the right.",
                  "length":0.094,
                  "verbal_transition_alert_instruction":"Take the exit on the right.",
                  "verbal_pre_transition_instruction":"Take the exit on the right."
               },

And in this, the exit should be right, not left:
![photo192226415749474601](https://cloud.githubusercontent.com/assets/5886786/10770092/bfc6fa54-7ce9-11e5-9e3a-85d3fa1ce62a.jpg)
OSM: http://www.openstreetmap.org/edit?editor=potlatch2#map=19/43.32598/-5.72942
               {
                  "begin_shape_index":175,
                  "street_names":[
                     "Enlace de Riaño"
                  ],
                  "time":25,
                  "type":21,
                  "end_shape_index":190,
                  "instruction":"Take the exit on the left.",
                  "length":0.531,
                  "verbal_transition_alert_instruction":"Take the exit on the left.",
                  "begin_street_names":[
                     "AS-117",
                     "Enlace de Riaño"
                  ],
                  "verbal_pre_transition_instruction":"Take the exit on the left."
               },

Thanks a lot in advance!

**Comment by dgearhart** [comment]
@costales i just checked in a fix for the roundabout count valhalla/mjolnir#312

**Comment by dgearhart** [comment]
@costales issue 2: is a data issue - i just fixed - the link was marked as a motorway_link instead of a motorway https://www.openstreetmap.org/way/40626360

**Comment by dgearhart** [comment]
@costales for item 3 - the left vs. right exit - are you saying the path is wrong? It should take the right lane instead of the left into the roundabout?

**Comment by costales** [comment]
Hi @dgearhart :)

1. Great!

2. Ops, thanks!

3. "It should take the right lane instead of the left into the roundabout", yes, but that it's not the issue, it could better, but it's OK.
The issue is: From 0,5km it will say you "turn left" and it's a real "turn right".
Take a look to this screenshot (same indication, but before the previous screenshot):
![photo192226415749474603](https://cloud.githubusercontent.com/assets/5886786/10771535/968a1894-7cf1-11e5-9d62-f7d906cccda4.jpg)

**Comment by dgearhart** [comment]
It seems odd to me that this way is marked as a motorway_link
http://www.openstreetmap.org/way/40626316
As you can see in the picture below - the current path is taking the motorway_link on the left (which is why it is saying exit on the left) - I think it should take the motorway_link on the right.

![screenshot from 2015-10-27 16 41 07](https://cloud.githubusercontent.com/assets/7515853/10771875/9af5d8be-7cc9-11e5-9cb1-4d6d5433bc2b.png)

@dnesbitt61 what say you?
