### ISSUE TITLE
Spatialite extension

### ISSUE THREAD

**Issue by molind** [valhalla/mjolnir#320]
There is an issue with spatialite extension library in Ubuntu 15.10. Spatialite changed way it loads as sqlite extension. They divided library to core library and sqlite module: https://www.gaia-gis.it/fossil/libspatialite/wiki?name=mod_spatialite

Now 

```
sql = "SELECT load_extension('libstatialite.so')";
```

won't load, because it don't have extension methods inside.

To fix this issue I just replaced it to:

```
sql = "SELECT load_extension('mod_spatialite')";
```

May be better solution would be set extension name as configure param. I'm not sure.

**Comment by ptpt** [comment]
Note that in Ubuntu 16.04, you need:

    sudo apt-get install libsqlite3-mod-spatialite

**Comment by kevinkreiser** [comment]
@ptpt is right, we do this when building packages for PPA: https://github.com/valhalla/packaging/blob/master/package.sh#L77

Sorry we're not supporting Ubuntu 15.10 as its not an LTS release. @molind if you can get onto 16.04 you can just install all of this stuff via PPA: https://launchpad.net/~valhalla-routing/+archive/ubuntu/valhalla

**Comment by molind** [comment]
Issue was reported 1.5 years ago. :) And Ubuntu 15.10 was most recent release. 

Everything is fine with last version.
https://github.com/valhalla/mjolnir/blob/9880d8e23c2ceffb8b33c5fbce784ee36ceff1d5/src/mjolnir/admin.cc#L30-L34

**Comment by kevinkreiser** [comment]
cool no worries, i just didnt want to make any assumptions about what distro you were on! thanks again!
