### ISSUE TITLE
area tags

### ISSUE THREAD

**Issue by gknisely** [valhalla/mjolnir#388]

**Comment by gknisely** [comment]
Do not toss areas that are rings.  Find test cases.

**Comment by dnesbitt61** [comment]
Disagree - I think most areas that are rings should be tossed. Aren't most areas rings or closed areas? We have no means of routing through areas (would create edges along the outside of the area which is likely not what we want - especially when areas share edges with roads.

**Comment by kevinkreiser** [comment]
i made another issue (simultanously it seems) which has more info, taginfo to be exact ;)

https://github.com/valhalla/mjolnir/issues/389
