### ISSUE TITLE
Shortcut Edges can remove ramp fork maneuvers

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/mjolnir#391]
Shortcut edges can cross nodes where ramps fork - thus preventing a maneuver from being generated when the shortcut edge is taken and inconcistency when shortcut edge is not taken. Add logic to prevent shortcut edges from crossing nodes where ramps fork.

**Comment by dnesbitt61** [comment]
One case is from Hershey,PA to Dulles,VA - the ramp from US-15S near Frederick misses Keep Left near the exit to Jefferson Pike.

**Comment by dnesbitt61** [comment]
We do not create shortcuts when either edge contains an exit sign - so these cases do not have exit signs. Perhaps we can mark nodes that have more than 2 links (and only links) as forks and then not create shortcuts through forks.

**Comment by dgearhart** [comment]
we do mark forks now - 
1) all edges are links
2) highway and no links
