### ISSUE TITLE
Move mjolnir section of valhalla.json

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/mjolnir#393]
Create a tile "description" file that describes the hierarchy. Alter graphreader to read this description and then alter tools to use this rather than reading the mjolnir conf section.

**Comment by kevinkreiser** [comment]
IMHO we should just build the structure of the tile into `baldr`. this takes away the ability/hassle to configure it but also, its important to notice we've never changed it once, and we still easily could but it it would be in code.
