### ISSUE TITLE
GraphTile NodeInfo index out of bounds

### ISSUE THREAD

**Issue by svenkreiss** [valhalla/mjolnir#437]
I am running `pbfadminbuilder` and `pbfgraphbuilder` on metro extracts. It works fine on the Liechtenstein extract that is in `tyr/test/data/liechtenstein-latest.osm.pbf`, but I get errors and warnings when running on metro extracts from https://mapzen.com/data/metro-extracts/, e.g. `san-francisco_california.osm.pbf`.

Some errors:

```sh
$ pbfadminbuilder
...
2016/04/06 17:28:38.424078 [INFO] Created admin table.
2016/04/06 17:28:38.424325 [ERROR] Standard exception processing relation: _Map_base::at
2016/04/06 17:28:38.424361 [INFO] Inserted 0 admin areas
...

$ pbfgraphbuilder
...
2016/04/06 17:30:10.195907 [INFO] Building 9 tiles with 1 threads...
2016/04/06 17:30:10.375986 [WARN] Exceeding max. edge length: 25602176
2016/04/06 17:30:10.496371 [WARN] Exceeding max. edge length: 25602388
(and many more messages like this)
...
2016/04/06 17:41:59.891413 [INFO] Validating signs and connectivity and binning edges
2016/04/06 17:42:00.042307 [ERROR] No opposing edge at LL=37.8279,-122.296 Length = 0 Startnode 2/736070/7 EndNode 2/736070/7 Shortcut 0
2016/04/06 17:42:00.042379 [WARN] No regular edges found from end node
2016/04/06 17:42:00.042409 [ERROR] No opposing edge at LL=37.8254,-122.31 Length = 0 Startnode 2/736070/8 EndNode 2/736070/8 Shortcut 0
(and many more messages like this)
```

And when I try to get a route, I get:
```
GraphTile NodeInfo index out of bounds: 734630,2,33412 nodecount= 31946
```

Any idea? Any other info I can provide?

**Comment by kevinkreiser** [comment]
generally we dont run an admin builder on an extract, the reason for that is extracts often don't have sufficient information to do it (important ways are missing). what happens when you remove the admin database file and run pbfraphbuilder on the extract in question?

**Comment by kevinkreiser** [comment]
seems there may be a problem with that extract. the liechtenstein one is from geofabrik which is wholely different than those from mapzen. we'll take a look at other extracts to see if we can confirm an issue for sure.

**Comment by gknisely** [comment]
Here is some more info on the pbfadminbuilder.  https://github.com/valhalla/mjolnir/blob/master/docs/getting_started_guide.md#administrative-areas

**Comment by dnesbitt61** [comment]
We are trying to track down the issue with importing Metro Extracts. In the meantime you can try using a download from GeoFabrik - like a state level extract: http://download.geofabrik.de/north-america/us/california.html. These seem to work fine.

**Comment by kevinkreiser** [comment]
it seems the extracts may have ways that reference nodes that arent present in the extract. our code is not yet robust to that. so we'll work on fixing it, using this issue!

**Comment by svenkreiss** [comment]
@dnesbitt61 thanks, confirmed. The geofabrik extracts do work fine.

**Comment by svenkreiss** [comment]
@kevinkreiser thanks
