### ISSUE TITLE
pbfadminbuilder failing

### ISSUE THREAD

**Issue by LEDominator** [valhalla/mjolnir#465]
I ran the valhalla-docker build script and it is failing with this error after compiling everything 

`Step 17 : RUN pbfadminbuilder -c conf/valhalla.json *.pbf
 ---> Running in f43fab39f1e6
/bin/sh: 1: pbfadminbuilder: not found`

**Comment by kevinkreiser** [comment]
yes we just merged some PRs that renamed things, this was one of those. I'll fix it!

**Comment by kevinkreiser** [comment]
ok i just pushed a commit there that should hopefully fix that. can you try it out and report back if its ok

**Comment by LEDominator** [comment]
That fixed it!  Thanks!
