### ISSUE TITLE
"Cannot reach destination - too far from a transit stop"

### ISSUE THREAD

**Issue by TommasoDb** [valhalla/mjolnir#545]
I'm trying to load Openstreetmap in Valhalla and calculate routes but I got the error: 
`{"code":400,"status":"Bad Request","error":"Cannot reach destination - too far from a transit stop"}`

I'm using the docker build (https://github.com/valhalla/docker) and Openstreetmap data from Geofabrik:  http://download.geofabrik.de/europe/germany/baden-wuerttemberg/karlsruhe-regbez-latest.osm.pbf

These are my step so far:

1. Start the server with:  
`VALHALLA_DOCKER_DATAPATH=/usr/local/programs/valhalla-docker-master/data docker-compose  -f docker-compose-source.yml up`

2. Then I log in the container and generate tiles using the command:
`valhalla_build_tiles -c conf/valhalla.json data/karlsruhe-regbez-latest.osm.pbf`
valhalla.json is the standard config file from https://raw.githubusercontent.com/valhalla/conf/ae9780d94f2eb890d9f6f5b705950e55ef92c727/valhalla.json ,  without modifications.
The tiles are saved in: /data/valhalla (on the docker container)

3. Now I try to request a route using the command (on the local machine):
`curl -g 'localhost:8002/route?json={"locations":[{"lat":49.4083606854431,"lon":8.68840834220934},{"lat":49.4089334018187,"lon":8.69187105072336}],"costing":"multimodal"}'`
but this returns:
`{"code":400,"status":"Bad Request","error":"Cannot reach destination - too far from a transit stop"}`

I also exported the edges using `valhalla_export_edges`  and loaded the data in QuantumGis, with the two start and end point as overlay. See image:
![valhalla](https://cloud.githubusercontent.com/assets/11291183/19387334/e7122264-9219-11e6-874e-daff75d7eb1e.png)

The red starts are the two points, the purple lines are the exported edges. As you can see, the points are exactly on a line. Why valhalla does return "too far from a transit stop"? What is that supposed to mean?
Maybe some sort of preprocessing of the OSM Data is needed?

**Comment by kevinkreiser** [comment]
ok yep your problem is you dont have any transit data. we get our transit data from transit.land via a tool called `valhalla_build_transit`. for your purposes you'll want to limit this tool to only getting a smaller bounding box of transit around Karlsruhe for example. I dont think we've yet added this to the tool yet but we should so people like you can have an easy time... So that one thing we'll need.

Then you'll need to point your `valhalla.json` config file at the location where `valhalla_build_transit` put the transit tiles. You'll see this defaulted to something in the `valhalla.json` config. After thats setup when you run `valhalla_build_tiles` you should get transit in your routing tiles :smile: 

So at this point I think we need to help you get a small extract of transit.land tiles via `valhalla_build_transit`. We'll keep you posted!

**Comment by kevinkreiser** [comment]
I should also note that I think our longer term plan will to just be to offer up transit tiles for the whole world somewhere in s3 or behind a cdn so no one has to make them directly as I mentioned above. If that turns out to be the case I'll point you to some docs for that as soon as we have them

**Comment by dnesbitt61** [comment]
Does your request work with one of the other costing methods: "costing":"auto" for example?

**Comment by TommasoDb** [comment]
Thanks for the responses. 
I started valhalla_build_transit but is still running. I'm getting many WARN 429, probably because I don't have a API key. Where can I get a key? I cannot find this information on https://transit.land

David, yes with "costing": "auto" it works, as well with bus, pedestrian and bicycle. Thank you very much

**Comment by kevinkreiser** [comment]
at present `valhalla_built_transit` is not ready for wide scale use. as you noted, without a key its not very useful. that is why i said i think we should give you the facility to get just small bounding box of transit (shouldnt hit key limitations) or just publish the already made transit tiles for you to download. ill talk with the rest of the team and we'll get back to you.

**Comment by TommasoDb** [comment]
Thanks. I think, this issue can be closed, but I have another question: I'm trying to use valhalla with self generated OSM data, also this mean, custom data exported as OSM pbf format. I need support for this, but probably this place is not the right one for this. Is there a mailing list too? Or should I open another issue?

**Comment by kevinkreiser** [comment]
That sounds good to me. Please open another issue with specific questions about custom data imports. Thanks again!
