### ISSUE TITLE
what():  blob-header-size is bigger than allowed 1010792557 > 65536

### ISSUE THREAD

**Issue by TommasoDb** [valhalla/mjolnir#547]
Im trying to load self generated osm data in valhalla, but **valhalla_build_tiles** raises this error:
```
2016/10/17 07:30:01.541770 [INFO] Parsing files: data/result.osm
2016/10/17 07:30:01.541900 [INFO] Parsing ways...
terminate called after throwing an instance of 'std::runtime_error'
  what():  blob-header-size is bigger than allowed 1010792557 > 65536

```
The data is only a small test dataset with a few lines. You can find it attached
[result.osm.zip](https://github.com/valhalla/mjolnir/files/532625/result.osm.zip)

I'm using the docker build (https://github.com/valhalla/docker) and the standard config file (https://raw.githubusercontent.com/valhalla/conf/ae9780d94f2eb890d9f6f5b705950e55ef92c727/valhalla.json) on Ubuntu 14.04:
`Linux HDMIH0394L 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
`
I started the docker container with this command:
`VALHALLA_DOCKER_DATAPATH=./data docker-compose  -f docker-compose-source.yml up`

**Comment by kevinkreiser** [comment]
we only support osm pbf format at this time. take your `.osm` and convert it to pbf with `osmconvert`. you can get that in ubuntu via `sudo apt-get install osmctools`. once your file is in proper osm pbf format `valhalla_built_tiles` should like it a lot better :wink:

**Comment by TommasoDb** [comment]
Thank you very much, it works
