### ISSUE TITLE
Segmentation fault with latest planet files

### ISSUE THREAD

**Issue by ericrwolfe** [valhalla/mjolnir#606]
I've been getting consistent segmentation faults with the latest planet files from http://planet.openstreetmap.org (both Jan 26 & Feb 1). 

```
2017/02/03 03:14:36.887454 [WARN] Speed = 150 wayId= 43053918
2017/02/03 03:14:36.887469 [WARN] Speed = 150 wayId= 43053918
2017/02/03 03:14:36.887516 [WARN] Speed = 150 wayId= 43053918
2017/02/03 03:14:36.887530 [WARN] Speed = 150 wayId= 43053918
2017/02/03 03:15:11.523213 [INFO] Finished
2017/02/03 03:15:15.294229 [INFO] Enhancing local graph...
Segmentation fault (core dumped)
```

Output from the 3 attempts here: https://gist.github.com/ericrwolfe/20af30839dfaf0d0006171399fb3a177

These are using the latest master branches of all of the mjolnir dependencies (as of 1/27 and 2/2) and a "good" admin.sqlite file obtained from @kevinkreiser after an error with `valhalla_build_admins` the first time around: `[ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract.`

The machines being used here are 8 core / 2.4GHz with 160GB SSD + 16gb ram. Seemingly no issues with memory (in fact I've never seen the memory usage go beyond 3gb or so), and the disk space at the time of the segfault with planet + output on the same disk:
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1       156G  138G   18G  89% /
```

Any ideas or help I can provide debugging here? @dnesbitt61

**Comment by ericrwolfe** [comment]
I should also note that I was able to run `valhalla_build_tiles` on an osm extract of California on the same machines before the planet attempts.

**Comment by gknisely** [comment]
Hey Eric,

First of all you should of never received the "sqlite3_step() error: NOT
NULL constraint failed: admin_access.admin_id. Ignore if not using a planet
extract." on a planet file.  This makes me believe that you may have a
spatialite issue.  Also, the first thing that the Enhancer does is load the
admin db.  Therefore, this could be crashing the enhancer if there is
a spatialite issue.

I noticed in your follow up email that you noted that California extract
worked for you.  Were you using the admin db for that conversion?

--Greg.

**Comment by ericrwolfe** [comment]
Yup, I was indeed using the admin db for the california extract.

Originally I'd received an `[ERROR] load_extension() error: mod_spatialite.so: cannot open shared object file: No such file or directory` at the end of running `valhalla_build_admins`. After installing `libsqlite3-mod-spatialite` I got the `sqlite3_step() error` above.

**Comment by ericrwolfe** [comment]
Hmm, I just reran on california and got a different segfault in shortcut generation: https://gist.github.com/ericrwolfe/99df55f2ed4f4b48971d709640dfd774

**Comment by kevinkreiser** [comment]
@ericrwolfe we've migrated over to the valhalla/valhalla repo can you reopen the issue over there?
